# Generated by Django 3.1.4 on 2021-04-23 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LHW_ReportsWise', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LHW_ReportsWise',
            new_name='LHW_ReportsWise_lhw_reportswise',
        ),
    ]
