# Generated by Django 3.1.4 on 2021-01-30 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('div_name', models.CharField(max_length=50)),
                ('Total_Cases', models.IntegerField()),
                ('Treatement_Completed', models.IntegerField()),
                ('Treatement_Incompleted', models.IntegerField()),
                ('No_of_Death', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Division',
            },
        ),
    ]
